### ISSUE TITLE
Tag view error: FieldError: Cannot resolve keyword u'discount' into field.

### ISSUE THREAD

**Issue by alexlittle** [mPowering/django-orb#439]
Got an automated error message (see below) - although this appears to be someone 'fiddling' with the url rather than a link on the site, but would be good to fix this so it doesn't generate a 500 error if the url params are played with.

```
Internal Server Error: /tag/view/safe-delivery
Traceback (most recent call last):
  File "/home/www/platform/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/www/platform/django-mpowering/orb/views.py", line 134, in tag_view
    'is_geo_tag': is_geo_tag,
  File "/home/www/platform/env/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/www/platform/env/lib/python2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/home/www/platform/env/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/home/www/platform/env/lib/python2.7/site-packages/django/template/base.py", line 210, in render
    return self._render(context)
  File "/home/www/platform/env/lib/python2.7/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/home/www/platform/env/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/www/platform/env/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/home/www/platform/env/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/www/platform/env/lib/python2.7/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/home/www/platform/env/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/www/platform/env/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/home/www/platform/env/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/www/platform/env/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/www/platform/env/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/home/www/platform/env/lib/python2.7/site-packages/django/template/defaulttags.py", line 328, in render
    if match:
  File "/home/www/platform/env/lib/python2.7/site-packages/django/db/models/query.py", line 170, in __nonzero__
    return type(self).__bool__(self)
  File "/home/www/platform/env/lib/python2.7/site-packages/django/db/models/query.py", line 166, in __bool__
    self._fetch_all()
  File "/home/www/platform/env/lib/python2.7/site-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/www/platform/env/lib/python2.7/site-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/home/www/platform/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 829, in execute_sql
    sql, params = self.as_sql()
  File "/home/www/platform/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 378, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup()
  File "/home/www/platform/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 49, in pre_sql_setup
    order_by = self.get_order_by()
  File "/home/www/platform/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 286, in get_order_by
    field, self.query.get_meta(), default_order=asc))
  File "/home/www/platform/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 558, in find_ordering_name
    field, targets, alias, joins, path, opts = self._setup_joins(pieces, opts, alias)
  File "/home/www/platform/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 591, in _setup_joins
    pieces, opts, alias)
  File "/home/www/platform/env/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1472, in setup_joins
    names, opts, allow_many, fail_on_missing=True)
  File "/home/www/platform/env/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1397, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
FieldError: Cannot resolve keyword u'discount' into field. Choices are: attribution, attribution_en, born_on, collectionresource, content_reviews, create_date, create_user, create_user_id, description, description_en, guid, id, image, resource, resource_related, resourcefile, resourcerating, resourcetag, resourcetracker, resourceurl, slug, source_host, source_name, source_peer, source_peer_id, source_url, status, study_time_number, study_time_unit, title, title_en, update_date, update_user, update_user_id, workflow_trackers

Request repr(): 
<WSGIRequest
path:/tag/view/safe-delivery,
GET:<QueryDict: {u'order_dir': [u'desc'], u'view_type': [u'grid'], u'brand': [u'Schesir'], u'page': [u'2'], u'per_page': [u'25'], u'order': [u'discount']}>,
POST:<QueryDict: {}>,
```

**Comment by bennylope** [comment]
This is currently in a "resolved" state but for some new tests that have proven finicky to get working together.
